name: Build C# application
on:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' # Вкажіть потрібну версію SDK
    - name: set folder
      run: cd UsersForms

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: UsersForms/bin/*
  